openapi: 3.0.0
info:
  title: ProductosSerivice API
  version: 1.0.0
  description: API para la gestión de Elementos-General
servers:
  - url: http://localhost:8080/evarest/rs
    description: Local Server

paths:
  /producto:
    post:
      summary: Crear un nuevo elemento
      operationId: guardarGeneral
      requestBody:
        description: Datos del elemento a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/General'
      responses:
        '201':
          description: Elemento creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      summary: Actualizar un Elemento existente
      operationId: actualizarGeneral
      requestBody:
        description: Datos del Elemento a actualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/General'
      responses:
        '200':
          description: Elemento actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/General'
        '404':
          description: Elemento no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Eliminar un Elemento
      operationId: borrarElemento
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: ID del Elemento a eliminar
      responses:
        '200':
          description: Elemento eliminado exitosamente
          content:
            application/json:
              schema:
                type: string
                example: "Elemento Eliminado"
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      summary: Obtener Elemento por Extra
      operationId: getElementoPorExtra
      parameters:
        - in: query
          name: codigo
          required: true
          schema:
            type: integer
            format: int32
          description: Código del Elemento a obtener
      responses:
        '200':
          description: Elemento encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/General'
        '404':
          description: Elemento no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /datos/list:
    get:
      summary: Obtener la lista de Elementos
      operationId: getGenerales
      responses:
        '200':
          description: Lista de Elementos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/General'
        '404':
          description: No se registran Elementos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:
    General:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        descripcion:
          type: string
        caracteristica:
          type: string
    ErrorMessage:
      type: object
      properties:
        codigo:
          type: integer
          example: 1
        mensaje:
          type: string
          example: ok